name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Install cargo-expand
        run: cargo install cargo-expand
      - name: Install nightly toolchain for cargo expand
        run: rustup toolchain install nightly
      - name: Install rustfmt for cargo expand
        run: rustup component add rustfmt --toolchain nightly
      - name: Run tests
        run: cargo test --verbose
